apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-testapp-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /new(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: new-testapp-frontend
                port:
                  number: 8085
