apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapp-frontend
spec:
  rules:
    - host: {{ .Values.testapp.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testapp-frontend
                port:
                  number: 8080
