apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapp-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /old(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: testapp-frontend
                port:
                  number: 8080
